export const CHANGE_STATUS = 'CHANGE_STATUS';
export const CHANGE_TAB_STATUS = 'CHANGE_TAB_STATUS';
export const CHANGE_ROSE_STATUS = 'CHANGE_ROSE_STATUS';
export const CHANGE_PHONE_STATUS = 'CHANGE_PHONE_STATUS';
export const CHANGE_HINT_STATUS = 'CHANGE_HINT_STATUS';
export const ADD_MESSAGES = 'ADD_MESSAGES';
export const CLOSE_INTRO = 'CLOSE_INTRO';